### ISSUE TITLE
Implement the Predator-Prey model

### ISSUE THREAD

**Issue by frnsys** [cybernetics-conference/cybersym#12]
The Predator-Prey (PP) model should consist of a few simple sub-models relating variables such as:

- humans
- animals
- etc

The relationships b/w variables should be parameterized too.

These variables and their relationships should be influenced by the monuments state (#5).

The PP state should have the format:

```
{
    'humans': 100,
    'animals': 200,
    'humans->animals': 2, # example relationship parameter 
    'animals->human': -1
}
```

**Comment by dantaeyoung** [comment]
The predator-prey model conceptualizes `relationships` between `actors`.

As noted in #8, the predator-prey **model** is computed from the state change of monuments. 
However, the model is run by the engine. AKA to use a Loopy metaphor: the model is the atemporal structure of relations between nodes/actors; the engine contains the update loop and makes everything run, and holds a temporal state.

The predator_prey engine is conceptually divided into four parts:

- monuments-to-relationships-logic (converts monument status to relationship model)
- relationship model (how actors relate to each other)
- world-state (actor status + relationships)
- pp engine (keeps everything running)

**Comment by dantaeyoung** [comment]
Currently working with commit d629d22.
