### ISSUE TITLE
Simulation description (1 paragraph)

### ISSUE THREAD

**Issue by frnsys** [cybernetics-conference/cybersym#28]
For the CyberCon program

**Comment by frnsys** [comment]
sketch:

> The CyberCon Simulation (_CyberSym_) connects attendee and speaker interations with Cybernetics Library to a virtual world of interconnected simple systems. When a book is checked out, the ideas contained within that book propagate through _The Plane of Monuments_, which mediates the real and the virtual, on into the simulated world, _TKTK_, manifesting as shocks, interventions, revolutions, and revelations that alter that world's dynamics and history. Views of these worlds will be projected so attendees can see the impact of the books they choose and watch the world unfold.

**Comment by dantaeyoung** [comment]
The CyberCon Simulation (*CyberSym*) creates a feedback loop between conference speakers and attendees, framing the conference itself as a cybernetic system.

*CyberSym* connects the Cybernetics Library to a virtual world of interconnected simple systems. When a Library Book is checked out, the ideas contained within that Book propagate through *The Plane of Monuments*, which mediates the real and the virtual; then into the simulated world, *The Sphere of Encounters*, manifesting as shocks, interventions, revolutions, and revelations that alter the world's dynamics and history. 

Views of these worlds will be projected, so attendees can see the impact of the books they choose and watch the world unfold. Finally, after each speaker, *The Planet of Encounters* will collectively formulate a question for each speaker to respond to

**Comment by frnsys** [comment]
this sounds great! I'll put it in the program
