### ISSUE TITLE
Visualize Monument from monument state

### ISSUE THREAD

**Issue by dantaeyoung** [cybernetics-conference/cybersym#4]
Written in JS
- [x] Should query `/monument` endpoint for monument state (#13)
- [x] Should represent monument states
- [x] Should detect change in monument state and express/animate/display monument state showily

**Comment by frnsys** [comment]
![image](https://user-images.githubusercontent.com/1059947/32411310-db0cd418-c1ad-11e7-9cbc-d98699bc2dfe.png)
