### ISSUE TITLE
Compute Predator-Prey state change from monuments state

### ISSUE THREAD

**Issue by frnsys** [cybernetics-conference/cybersym#8]
Given a monuments state (see #5), the PP state should be updated. It should be a transient input into the PP model (#12)

**Comment by dantaeyoung** [comment]
Completed with commit d629d22. Predator-prey graph edges (not the states, just the weights of relationships) is (currently) purely a result of monument state. Therefore, at any given moment, monument state should be enough to describe all of the graph relations.
